In [11]:
import tensorflow as tf
import numpy as np

#create a linear model to find the difference between three different flowers

#iris setosa
#iris veriscolour
#iris virginica

from tensorflow.contrib.learn.python.learn.datasets import base

IRIS_TRAINING = "./iris_training.csv"
IRIS_TEST = "./iris_test.csv"
#training set is taking from the iris_training.csv file features are stored in a separate data set along with the target dtype
training_set = base.load_csv_with_header(filename=IRIS_TRAINING, features_dtype = np.float32, target_dtype=np.int)

test_set = base.load_csv_with_header(filename=IRIS_TEST, features_dtype = np.float32, target_dtype=np.int)

print(test_set.data)
print(test_set.target)

[[5.9 3.  4.2 1.5]
 [5.2 3.  4.1 1.5]
 [5.9 3.  4.2 1.5]
 [5.2 3.  4.1 1.5]
 [5.9 3.  4.2 1.5]
 [5.2 3.  4.1 1.5]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]]
[1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [12]:
feature_name = "flower_features"

feature_columns = [tf.feature_column.numeric_column(feature_name, shape=[4])]

classifier = tf.estimator.LinearClassifier(feature_columns = feature_columns, n_classes = 3, model_dir="./iris_model")

def input_fn(dataset):
    def _fn():
        features={feature_name: tf.constant(dataset.data)}
        label = tf.constant(dataset.target)
        return features, label
    return _fn

def eval_input_fn(features, batch_size):
    # Convert the inputs to a Dataset.
    dataset = tf.data.Dataset.from_tensor_slices(features)
    # Return the dataset.
    return dataset


#takes the data and sorts out features and labels into model

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7ff73ff7d7f0>, '_master': '', '_service': None, '_tf_random_seed': None, '_log_step_count_steps': 100, '_evaluation_master': '', '_keep_checkpoint_max': 5, '_save_summary_steps': 100, '_num_ps_replicas': 0, '_is_chief': True, '_save_checkpoints_steps': None, '_global_id_in_cluster': 0, '_task_id': 0, '_session_config': None, '_task_type': 'worker', '_num_worker_replicas': 1, '_save_checkpoints_secs': 600, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': './iris_model'}


In [13]:
classifier.train(input_fn = input_fn(test_set), steps = 1000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ./iris_model/model.ckpt-7000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 7001 into ./iris_model/model.ckpt.
INFO:tensorflow:step = 7001, loss = 38.10005
INFO:tensorflow:global_step/sec: 538.308
INFO:tensorflow:step = 7101, loss = 1.8938832 (0.192 sec)
INFO:tensorflow:global_step/sec: 654.818
INFO:tensorflow:step = 7201, loss = 0.9402256 (0.148 sec)
INFO:tensorflow:global_step/sec: 704.521
INFO:tensorflow:step = 7301, loss = 0.62343955 (0.144 sec)
INFO:tensorflow:global_step/sec: 716.251
INFO:tensorflow:step = 7401, loss = 0.46587002 (0.138 sec)
INFO:tensorflow:global_step/sec: 656.747
INFO:tensorflow:step = 7501, loss = 0.37172556 (0.154 sec)
INFO:tensorflow:global_step/sec: 737.745
INFO:tensorflow:step = 7601, loss 

In [14]:
accuracy_score =  classifier.evaluate(input_fn(test_set), steps=100)["accuracy"]
predict = classifier.predict(input_fn(test_set))
expected = ['Setosa', 'Versicolor', 'Virginica']

print("\nAccuracy: {0:f}".format(accuracy_score))

for p in predict:
    class_id = p['class_ids'][0]
    probability = p['probabilities'][class_id]
    print('\nPrediction is "{}"'.format(p))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2018-07-01-15:57:15
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ./iris_model/model.ckpt-8000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [10/100]
INFO:tensorflow:Evaluation [20/100]
INFO:tensorflow:Evaluation [30/100]
INFO:tensorflow:Evaluation [40/100]
INFO:tensorflow:Evaluation [50/100]
INFO:tensorflow:Evaluation [60/100]
INFO:tensorflow:Evaluation [70/100]
INFO:tensorflow:Evaluation [80/100]
INFO:tensorflow:Evaluation [90/100]
INFO:tensorflow:Evaluation [100/100]
INFO:tensorflow:Finished evaluation at 2018-07-01-15:57:15
INFO:tensorflow:Saving dict for global step 8000: accuracy = 1.0, average_loss = 0.0061546587, global_step = 8000, loss = 0.18463975

Accuracy: 1.000000
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was final


Prediction is "{'logits': array([-3.95117  ,  3.8094687, -5.156582 ], dtype=float32), 'probabilities': array([4.2594835e-04, 9.9944645e-01, 1.2760068e-04], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-4.2336187,  2.8170729, -3.9381008], dtype=float32), 'probabilities': array([8.6505187e-04, 9.9797255e-01, 1.1624759e-03], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-3.95117  ,  3.8094687, -5.156582 ], dtype=float32), 'probabilities': array([4.2594835e-04, 9.9944645e-01, 1.2760068e-04], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-4.2336187,  2.8170729, -3.9381008], dtype=float32), 'probabilities': array([8.6505187e-04, 9.9797255e-01, 1.1624759e-03], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-3.95117  

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,


Prediction is "{'logits': array([-3.95117  ,  3.8094687, -5.156582 ], dtype=float32), 'probabilities': array([4.2594835e-04, 9.9944645e-01, 1.2760068e-04], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-4.2336187,  2.8170729, -3.9381008], dtype=float32), 'probabilities': array([8.6505187e-04, 9.9797255e-01, 1.1624759e-03], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-3.95117  ,  3.8094687, -5.156582 ], dtype=float32), 'probabilities': array([4.2594835e-04, 9.9944645e-01, 1.2760068e-04], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-4.2336187,  2.8170729, -3.9381008], dtype=float32), 'probabilities': array([8.6505187e-04, 9.9797255e-01, 1.1624759e-03], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-3.95117  


Prediction is "{'logits': array([-3.95117  ,  3.8094687, -5.156582 ], dtype=float32), 'probabilities': array([4.2594835e-04, 9.9944645e-01, 1.2760068e-04], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-4.2336187,  2.8170729, -3.9381008], dtype=float32), 'probabilities': array([8.6505187e-04, 9.9797255e-01, 1.1624759e-03], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-3.95117  ,  3.8094687, -5.156582 ], dtype=float32), 'probabilities': array([4.2594835e-04, 9.9944645e-01, 1.2760068e-04], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-4.2336187,  2.8170729, -3.9381008], dtype=float32), 'probabilities': array([8.6505187e-04, 9.9797255e-01, 1.1624759e-03], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-3.95117  


Prediction is "{'logits': array([-3.95117  ,  3.8094687, -5.156582 ], dtype=float32), 'probabilities': array([4.2594835e-04, 9.9944645e-01, 1.2760068e-04], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-4.2336187,  2.8170729, -3.9381008], dtype=float32), 'probabilities': array([8.6505187e-04, 9.9797255e-01, 1.1624759e-03], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-3.95117  ,  3.8094687, -5.156582 ], dtype=float32), 'probabilities': array([4.2594835e-04, 9.9944645e-01, 1.2760068e-04], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-4.2336187,  2.8170729, -3.9381008], dtype=float32), 'probabilities': array([8.6505187e-04, 9.9797255e-01, 1.1624759e-03], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-3.95117  

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([-3.95117  ,  3.8094687, -5.156582 ], dtype=float32), 'probabilities': array([4.2594835e-04, 9.9944645e-01, 1.2760068e-04], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-4.2336187,

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,


Prediction is "{'logits': array([-3.95117  ,  3.8094687, -5.156582 ], dtype=float32), 'probabilities': array([4.2594835e-04, 9.9944645e-01, 1.2760068e-04], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-4.2336187,  2.8170729, -3.9381008], dtype=float32), 'probabilities': array([8.6505187e-04, 9.9797255e-01, 1.1624759e-03], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-3.95117  ,  3.8094687, -5.156582 ], dtype=float32), 'probabilities': array([4.2594835e-04, 9.9944645e-01, 1.2760068e-04], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-4.2336187,  2.8170729, -3.9381008], dtype=float32), 'probabilities': array([8.6505187e-04, 9.9797255e-01, 1.1624759e-03], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-3.95117  

Prediction is "{'logits': array([-3.95117  ,  3.8094687, -5.156582 ], dtype=float32), 'probabilities': array([4.2594835e-04, 9.9944645e-01, 1.2760068e-04], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-4.2336187,  2.8170729, -3.9381008], dtype=float32), 'probabilities': array([8.6505187e-04, 9.9797255e-01, 1.1624759e-03], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-3.95117  ,  3.8094687, -5.156582 ], dtype=float32), 'probabilities': array([4.2594835e-04, 9.9944645e-01, 1.2760068e-04], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-4.2336187,  2.8170729, -3.9381008], dtype=float32), 'probabilities': array([8.6505187e-04, 9.9797255e-01, 1.1624759e-03], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}"

Prediction is "{'logits': array([-3.95117  ,

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,  1.1183912, -6.1053333], dtype=float32), 'probabilities': array([9.9265665e-01, 7.3379818e-03, 5.3499903e-06], dtype=float32), 'class_ids': array([0]), 'classes': array([b'0'], dtype=object)}"

Prediction is "{'logits': array([ 6.025712 ,

KeyboardInterrupt: 